In [25]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets

In [26]:
digits = datasets.load_digits()
breast_cancer = datasets.load_breast_cancer()

In [27]:
from sklearn import datasets, cross_validation, naive_bayes

In [28]:
X_digits = digits.data
y_digits = digits.target

X_cancer = breast_cancer.data
y_cancer = breast_cancer.target

In [37]:
digits.data

array([[  0.,   0.,   5., ...,   0.,   0.,   0.],
       [  0.,   0.,   0., ...,  10.,   0.,   0.],
       [  0.,   0.,   0., ...,  16.,   9.,   0.],
       ..., 
       [  0.,   0.,   1., ...,   6.,   0.,   0.],
       [  0.,   0.,   2., ...,  12.,   0.,   0.],
       [  0.,   0.,  10., ...,  12.,   1.,   0.]])

In [38]:
breast_cancer.data

array([[  1.79900000e+01,   1.03800000e+01,   1.22800000e+02, ...,
          2.65400000e-01,   4.60100000e-01,   1.18900000e-01],
       [  2.05700000e+01,   1.77700000e+01,   1.32900000e+02, ...,
          1.86000000e-01,   2.75000000e-01,   8.90200000e-02],
       [  1.96900000e+01,   2.12500000e+01,   1.30000000e+02, ...,
          2.43000000e-01,   3.61300000e-01,   8.75800000e-02],
       ..., 
       [  1.66000000e+01,   2.80800000e+01,   1.08300000e+02, ...,
          1.41800000e-01,   2.21800000e-01,   7.82000000e-02],
       [  2.06000000e+01,   2.93300000e+01,   1.40100000e+02, ...,
          2.65000000e-01,   4.08700000e-01,   1.24000000e-01],
       [  7.76000000e+00,   2.45400000e+01,   4.79200000e+01, ...,
          0.00000000e+00,   2.87100000e-01,   7.03900000e-02]])

In [39]:
digits.target

array([0, 1, 2, ..., 8, 9, 8])

In [40]:
breast_cancer.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 0,

In [29]:
clf1 = naive_bayes.BernoulliNB()
clf2 = naive_bayes.MultinomialNB()
clf3 = naive_bayes.GaussianNB()

In [30]:
ans1 = cross_validation.cross_val_score(clf1, X_digits, y_digits, scoring='accuracy', cv=10).mean()
ans2 = cross_validation.cross_val_score(clf2, X_digits, y_digits, scoring='accuracy', cv=10).mean()
ans3 = cross_validation.cross_val_score(clf3, X_digits, y_digits, scoring='accuracy', cv=10).mean()
print('cvs_mean with BernoulliNB = {}\ncvs_mean with MultinominalNB = {}\ncvs_mean with GaussianNB = {}'.format(ans1, ans2, ans3))

cvs_mean with BernoulliNB = 0.831855746495016
cvs_mean with MultinominalNB = 0.8819396216300838
cvs_mean with GaussianNB = 0.8103537583567821


In [32]:
ans4 = cross_validation.cross_val_score(clf1, X_cancer, y_cancer, scoring='accuracy', cv=10).mean()
ans5 = cross_validation.cross_val_score(clf2, X_cancer, y_cancer, scoring='accuracy', cv=10).mean()
ans6 = cross_validation.cross_val_score(clf3, X_cancer, y_cancer, scoring='accuracy', cv=10).mean()
print('cvs_mean with BernoulliNB = {}\ncvs_mean with MultinominalNB = {}\ncvs_mean with GaussianNB = {}'.format(ans4, ans5, ans6))

cvs_mean with BernoulliNB = 0.6274274047186933
cvs_mean with MultinominalNB = 0.8929349235156856
cvs_mean with GaussianNB = 0.9386796733212339


In [33]:
def write_answer_to_file(answer, filename):
    with open(filename, 'w') as f_out:
        f_out.write(str(answer))

In [36]:
write_answer_to_file(ans1, '1.txt')

In [ ]:
write_answer_to_file(ans5, '2.txt')

In [35]:
write_answer_to_file('2 3', '3.txt')